# version: '3.8'

# services:
#   zookeeper1:
#     image: confluentinc/cp-zookeeper:7.4.0
#     hostname: zookeeper1
#     container_name: zookeeper1
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888
#     ports:
#       - "2181:2181"

#   zookeeper2:
#     image: confluentinc/cp-zookeeper:7.4.0
#     hostname: zookeeper2
#     container_name: zookeeper2
#     environment:
#       ZOOKEEPER_SERVER_ID: 2
#       ZOOKEEPER_CLIENT_PORT: 2182
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888
#     ports:
#       - "2182:2182"

#   kafka1:
#     image: confluentinc/cp-kafka:7.4.0
#     hostname: kafka1
#     container_name: kafka1
#     depends_on:
#       - zookeeper1
#       - zookeeper2
#     ports:
#       - "9092:9092"
#     environment:
#       # KAFKA_BROKER_ID: 1
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
#       # # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9092
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       # KAFKA_BROKER_ID: 1
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
#       # # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       # # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
#       # # KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
#       # # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

#       # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,DOCKER://kafka1:29093
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
#       # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,DOCKER://0.0.0.0:29093
#       # KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

#       KAFKA_BROKER_ID: 1
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,DOCKER://kafka1:29093
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,DOCKER://0.0.0.0:29093
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER



#   kafka2:
#     image: confluentinc/cp-kafka:7.4.0
#     hostname: kafka2
#     container_name: kafka2
#     depends_on:
#       - zookeeper1
#       - zookeeper2
#     ports:
#       - "9093:9093"
#     environment:
#       # KAFKA_BROKER_ID: 2
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
#       # # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
#       # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9093,PLAINTEXT_HOST://localhost:9093
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       # KAFKA_BROKER_ID: 2
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29093,EXTERNAL://localhost:9093
#       # KAFKA_LISTENERS: INTERNAL://0.0.0.0:29093,EXTERNAL://0.0.0.0:9093
#       # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

#       KAFKA_BROKER_ID: 2
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092,DOCKER://kafka2:39093
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092,DOCKER://0.0.0.0:39093
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER



#   kafka3:
#     image: confluentinc/cp-kafka:7.4.0
#     hostname: kafka3
#     container_name: kafka3
#     depends_on:
#       - zookeeper1
#       - zookeeper2
#     ports:
#       - "9094:9094"
#     environment:
#       # KAFKA_BROKER_ID: 3
#       # KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29094,EXTERNAL://localhost:9094
#       # KAFKA_LISTENERS: INTERNAL://0.0.0.0:29094,EXTERNAL://0.0.0.0:9094
#       # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

#       KAFKA_BROKER_ID: 3
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:49092,DOCKER://kafka3:49093
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:49092,DOCKER://0.0.0.0:49093
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER


version: '3.8'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888

  zookeeper3:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,DOCKER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,DOCKER://kafka1:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092,DOCKER://0.0.0.0:39093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092,DOCKER://kafka2:39093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "49092:49092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:49092,DOCKER://0.0.0.0:49093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:49092,DOCKER://kafka3:49093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
